list: $/yamobile/thirdpartycode/models/targets/columns.yaml
modelClass: Yamobile\ThirdPartyCode\Models\Targets
title: Targets
noRecordsMessage: "backend::lang.list.no_records"
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
  buttons: list_toolbar
  search:
    prompt: "backend::lang.list.search_prompt"
recordUrl: "yamobile/thirdpartycode/targets/update/:id"
