name: Targets
form: $/yamobile/thirdpartycode/models/targets/fields.yaml
modelClass: Yamobile\ThirdPartyCode\Models\Targets
defaultRedirect: yamobile/thirdpartycode/targets
create:
  redirect: "yamobile/thirdpartycode/targets/update/:id"
  redirectClose: yamobile/thirdpartycode/targets
update:
  redirect: yamobile/thirdpartycode/targets
  redirectClose: yamobile/thirdpartycode/targets
